apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-calculator
  namespace: testing-env
spec:
  selector:
    matchLabels:
      app: java-web-calculator
  template:
    metadata:
      labels:
        app: java-web-calculator
    spec:
      containers:
      - name: java-web-calculator-container
        image: gmk1995/java-web-calculator:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-calculator-service
  namespace: testing-env
spec:
  selector:
    app: java-web-calculator
  ports:
  - port: 80
    targetPort: 8080

